[build]
  base = "app"
  command = "npm run build"
  functions = "app/src/functions"
  publish = "app/dist"

[dev]
  framework = "#custom"
  command = "npm run serve" # Command to start your dev server
  targetPort = 8080 # The port for your application server, framework or site generator
  port = 8888 # The port that the netlify dev will be accessible on
  publish = "public" # The path to your static content folder
  autoLaunch = true